# Generated by Django 5.2.1 on 2025-05-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='fecha_actualizacion',
        ),
    ]
