# Generated by Django 5.2.1 on 2025-06-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_remove_rol_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('consumidor', 'Consumidor'), ('pasante', 'Pasante'), ('liderup', 'Lider de unidad productiva'), ('vocera', 'Vocera'), ('administrador', 'Administrador')], max_length=20, unique=True),
        ),
    ]
