# Generated by Django 5.2.1 on 2025-07-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_alter_rol_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('consumidor', 'Consumidor'), ('pasante', 'Pasante'), ('liderup', 'Lider de unidad productiva'), ('vocera', 'Vocera'), ('administrador', 'Administrador'), ('cajero', 'Cajero')], max_length=20, unique=True),
        ),
    ]
