# Generated by Django 5.2.1 on 2025-05-14 02:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('precios', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('devolucion', 'Devolucion'), ('ajuste', 'Ajuste')], default='venta', max_length=20)),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.precio')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona')),
            ],
        ),
    ]
