# Generated by Django 5.2.1 on 2025-06-23 21:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_diaria', '0002_initial'),
        ('productos', '0006_remove_producto_capacidad_diaria_and_more'),
        ('transaccion', '0002_remove_transaccion_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='transaccion_revertida',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='caja_diaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja_diaria.cajadiaria'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra')], max_length=10),
        ),
    ]
