# Generated by Django 5.2.1 on 2025-07-16 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0004_remove_transaccion_monto_venta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalletransaccion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalletransaccion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
