# Generated by Django 5.2.1 on 2025-07-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0005_alter_detalletransaccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletransaccion',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
