# Generated by Django 5.2.1 on 2025-05-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion_principal', models.TextField()),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sena/empresa/logos/', verbose_name='Logo institucional')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Empresa activa?')),
            ],
        ),
    ]
