# Generated by Django 5.2.1 on 2025-06-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_caja', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecaja',
            old_name='caja_id',
            new_name='caja',
        ),
        migrations.RenameField(
            model_name='detallecaja',
            old_name='transaccion_id',
            new_name='transaccion',
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=50),
        ),
    ]
