# Generated by Django 5.2.1 on 2025-07-24 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_diaria', '0004_alter_cajadiaria_saldo_final'),
        ('detalle_caja', '0003_rename_caja_id_detallecaja_caja_and_more'),
        ('transaccion', '0006_detalletransaccion_nombre_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecaja',
            options={'ordering': ['-fecha'], 'verbose_name': 'Detalle de Caja', 'verbose_name_plural': 'Detalles de Caja'},
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='caja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja_diaria.cajadiaria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaccion.transaccion'),
        ),
    ]
