# Generated by Django 5.1 on 2025-07-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_caja', '0004_alter_detallecaja_options_detallecaja_beneficiario_and_more'),
        ('productos', '0008_producto_tiene_comision'),
        ('transaccion', '0006_detalletransaccion_nombre_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecaja',
            options={},
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='monto',
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='transaccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_caja', to='transaccion.transaccion'),
            preserve_default=False,
        ),
    ]
