# Generated by Django 5.2.1 on 2025-07-27 03:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_diaria', '0006_remove_cajadiaria_diferencia_efectivo'),
        ('detalle_caja', '0005_alter_detallecaja_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecaja',
            options={'ordering': ['-creado']},
        ),
        migrations.RenameField(
            model_name='detallecaja',
            old_name='precio_unitario',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallecaja',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='caja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja_diaria.cajadiaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
