# Generated by Django 5.2.1 on 2025-05-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='unidades/logos/%Y/%m/%d/')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('agricola', 'Agricola'), ('agroindustria', 'Agroindustria'), ('gastronomia', 'Gastronomia'), ('pecuaria', 'Pecuaria'), ('escuelanacionalcafe', 'Escuela Nacional del Café'), ('ambiental', 'Ambiental'), ('empresaserviciopublicos', 'Servicios Publicos'), ('moda', 'Moda')], max_length=25)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En mantenimiento')], default='activa', max_length=20)),
                ('horario_atencion', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
            ],
        ),
    ]
