# Generated by Django 5.2.1 on 2025-07-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_productivas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadproductiva',
            name='tipo',
            field=models.CharField(choices=[('agricola', 'Agricola'), ('agroindustria', 'Agroindustria'), ('gastronomia', 'Gastronomia'), ('pecuaria', 'Pecuaria'), ('escuelanacionalcafe', 'Escuela Nacional del Café'), ('ambiental', 'Ambiental'), ('empresaserviciopublicos', 'Servicios Publicos'), ('moda', 'Moda'), ('tiendaY', 'Tienda Yamboro')], max_length=25),
        ),
    ]
