# Generated by Django 5.2.1 on 2025-07-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_alter_sede_sena_empresa'),
        ('unidades_productivas', '0002_alter_unidadproductiva_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadproductiva',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_productivas', to='sede.sede'),
        ),
    ]
