# Generated by Django 5.2.1 on 2025-07-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_productivas', '0003_alter_unidadproductiva_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadproductiva',
            name='nombre',
        ),
    ]
