# Generated by Django 5.2.1 on 2025-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades_productivas', '0005_alter_unidadproductiva_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadproductiva',
            name='estado',
        ),
        migrations.AddField(
            model_name='unidadproductiva',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Unidad activa?'),
        ),
    ]
