# Generated by Django 5.2.1 on 2025-06-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='precio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=10),
            preserve_default=False,
        ),
    ]
