# Generated by Django 5.2.1 on 2025-07-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_precio_reserva_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('entregada', 'Entregada'), ('fiado', 'Fiado')], default='pendiente', max_length=20),
        ),
    ]
