# Generated by Django 5.2.1 on 2025-05-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja_diaria', '0001_initial'),
        ('persona', '0001_initial'),
        ('unidades_productivas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='abierta_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_abiertas', to='persona.persona'),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to='persona.persona'),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='unidadProductiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades_productivas.unidadproductiva'),
        ),
    ]
