# Generated by Django 5.2.1 on 2025-07-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_diaria', '0004_alter_cajadiaria_saldo_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='diferencia_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia de efectivo'),
        ),
    ]
