# Generated by Django 5.1 on 2025-07-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja_diaria', '0005_cajadiaria_diferencia_efectivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajadiaria',
            name='diferencia_efectivo',
        ),
    ]
