# Generated by Django 5.2.1 on 2025-05-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_options_alter_persona_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='persona',
            managers=[
            ],
        ),
    ]
