# Generated by Django 5.2.1 on 2025-07-07 18:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0008_producto_tiene_comision'),
        ('unidades_productivas', '0002_alter_unidadproductiva_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('abono_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_fiadas', to='productos.producto')),
                ('unidad_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_fiadas', to='unidades_productivas.unidadproductiva')),
            ],
            options={
                'verbose_name': 'Detalle de Cartera',
                'verbose_name_plural': 'Detalles de Cartera',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AbonoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detalle_cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cartera.detallecartera')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
