# Generated by Django 5.2.1 on 2025-06-02 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='persona',
        ),
        migrations.AddField(
            model_name='precio',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo'),
            preserve_default=False,
        ),
    ]
