# Generated by Django 5.2.1 on 2025-05-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sena_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('centro', 'Centro'), ('yamboro', 'Yamboro')], max_length=20, unique=True)),
                ('direccion', models.TextField(verbose_name='Dirección completa')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable de sede')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Sede activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sena_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sena_empresa.senaempresa')),
            ],
        ),
    ]
