# Generated by Django 5.2.1 on 2025-05-25 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
        ('sena_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='sena_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='sena_empresa.senaempresa'),
        ),
    ]
