# Generated by Django 5.2.1 on 2025-07-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_alter_sede_sena_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
