# Generated by Django 5.2.1 on 2025-05-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('unidades_productivas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=20)),
                ('tipo_gestion', models.CharField(choices=[('stock', 'Gestión por stock'), ('produccion', 'Producción diaria (almuerzos)')], default='con_stock', max_length=20)),
                ('reservas', models.CharField(choices=[('si', 'Requiere reserva'), ('no', 'No requiere reserva')], default='no', max_length=20)),
                ('stock_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('capacidad_diaria', models.PositiveIntegerField(blank=True, help_text='Para productos sin stock (ej: almuerzos)', null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='producto_images/')),
                ('unidad_medida_base', models.CharField(choices=[('unidad', 'Unidades'), ('gramos', 'Gramos'), ('ml', 'Mililitros'), ('kg', 'Kilogramos'), ('litro', 'Litros')], default='unidad', max_length=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.tipocategoria')),
                ('unidadP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades_productivas.unidadproductiva')),
            ],
        ),
    ]
