# Generated by Django 5.2.1 on 2025-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.CharField(choices=[('si', 'Tiene descuento'), ('no', 'No Tiene descuento')], default='no', max_length=20),
        ),
    ]
