# Generated by Django 5.2.1 on 2025-05-30 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.AddField(
            model_name='producto',
            name='hora_limite_reserva',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
    ]
