# Generated by Django 5.2.1 on 2025-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='reservas',
            field=models.BooleanField(default=True),
        ),
    ]
