# Generated by Django 5.2.1 on 2025-06-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='capacidad_diaria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_gestion',
        ),
        migrations.AddField(
            model_name='producto',
            name='max_reservas',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de reservas permitidas', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(blank=True, help_text='Solo para productos que manejan stock', null=True),
        ),
    ]
