# Generated by Django 5.1 on 2025-07-03 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_producto_capacidad_diaria_and_more'),
        ('unidades_productivas', '0002_alter_unidadproductiva_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_comision_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidades_productivas.unidadproductiva'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to='unidades_productivas.unidadproductiva'),
        ),
    ]
