# Generated by Django 5.1 on 2025-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_producto_comision_producto_unidad_comision_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_comision',
            field=models.BooleanField(default=False),
        ),
    ]
